<div class="wrap"><p id="aboutMe">My name is Johnathan Stadtmueller and I enjoy a good time. I enjoy seeing travelling, outdoorsy adventures and other things alike.
I am on a journey currently to knock as many items off of my bucket list as possible and have been doing it for a while now!
This includes what my other web pages include such as music festivals. I am attending another one on the 14th and 15th of September and
cannot wait!</p>
<img src="https://images.pexels.com/photos/457882/pexels-photo-457882.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500" alt="beach" /></div>